--
-- PostgreSQL database dump
--

\restrict xWreKFfFtnJhjRqiXQPRHd51pqzu3UPFzcbWT5Ms4kOuS9YXuoTo5fB3W9dXGis

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


--
-- Name: release_tour_spots(uuid, uuid, integer); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.release_tour_spots(p_tour_id uuid, p_tour_date_id uuid, p_participants integer) RETURNS boolean
    LANGUAGE plpgsql
    AS $$
BEGIN
    -- Si hay tour_date_id, trabajar con tour_dates
    IF p_tour_date_id IS NOT NULL THEN
        UPDATE tour_dates
        SET available_spots = LEAST(
            available_spots + p_participants,
            (SELECT max_capacity FROM tours WHERE id = p_tour_id)
        ),
        updated_at = CURRENT_TIMESTAMP
        WHERE id = p_tour_date_id;
        
        RETURN TRUE;
    ELSE
        -- Trabajar con tours directamente
        UPDATE tours
        SET available_spots = LEAST(
            available_spots + p_participants,
            max_capacity
        ),
        updated_at = CURRENT_TIMESTAMP
        WHERE id = p_tour_id;
        
        RETURN TRUE;
    END IF;
END;
$$;


--
-- Name: reserve_tour_spots(uuid, uuid, integer); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.reserve_tour_spots(p_tour_id uuid, p_tour_date_id uuid, p_participants integer) RETURNS boolean
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_available_spots INTEGER;
    v_max_capacity INTEGER;
BEGIN
    -- Si hay tour_date_id, trabajar con tour_dates
    IF p_tour_date_id IS NOT NULL THEN
        SELECT available_spots INTO v_available_spots
        FROM tour_dates
        WHERE id = p_tour_date_id
          AND is_active = true
        FOR UPDATE; -- Lock row para prevenir race conditions
        
        IF v_available_spots IS NULL THEN
            RETURN FALSE; -- Tour date no existe o no estÃ¡ activo
        END IF;
        
        IF v_available_spots < p_participants THEN
            RETURN FALSE; -- No hay suficientes cupos
        END IF;
        
        -- Actualizar cupos disponibles
        UPDATE tour_dates
        SET available_spots = available_spots - p_participants,
            updated_at = CURRENT_TIMESTAMP
        WHERE id = p_tour_date_id;
        
        RETURN TRUE;
    ELSE
        -- Trabajar con tours directamente
        SELECT available_spots, max_capacity INTO v_available_spots, v_max_capacity
        FROM tours
        WHERE id = p_tour_id
          AND is_active = true
        FOR UPDATE; -- Lock row
        
        IF v_available_spots IS NULL THEN
            RETURN FALSE; -- Tour no existe o no estÃ¡ activo
        END IF;
        
        IF v_available_spots < p_participants THEN
            RETURN FALSE; -- No hay suficientes cupos
        END IF;
        
        -- Actualizar cupos disponibles
        UPDATE tours
        SET available_spots = available_spots - p_participants,
            updated_at = CURRENT_TIMESTAMP
        WHERE id = p_tour_id;
        
        RETURN TRUE;
    END IF;
END;
$$;


--
-- Name: update_updated_at_column(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: DataProtectionKeys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."DataProtectionKeys" (
    "Id" integer NOT NULL,
    "FriendlyName" text,
    "Xml" text
);


--
-- Name: DataProtectionKeys_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."DataProtectionKeys" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DataProtectionKeys_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid,
    entity_type character varying(100) NOT NULL,
    entity_id uuid NOT NULL,
    action character varying(50) NOT NULL,
    before_state jsonb,
    after_state jsonb,
    ip_address character varying(45),
    user_agent text,
    correlation_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT chk_action CHECK (((action)::text = ANY (ARRAY[('CREATE'::character varying)::text, ('UPDATE'::character varying)::text, ('DELETE'::character varying)::text, ('READ'::character varying)::text, ('LOGIN'::character varying)::text, ('LOGOUT'::character varying)::text, ('PAYMENT'::character varying)::text, ('CANCEL'::character varying)::text])))
);


--
-- Name: booking_participants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.booking_participants (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    booking_id uuid NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    email character varying(255),
    phone character varying(20),
    date_of_birth date,
    special_requirements text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT chk_email_format_participant CHECK (((email IS NULL) OR ((email)::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text)))
);


--
-- Name: bookings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookings (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    tour_id uuid NOT NULL,
    tour_date_id uuid,
    status integer DEFAULT 1 NOT NULL,
    number_of_participants integer NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    expires_at timestamp without time zone,
    notes text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone,
    country_id uuid,
    CONSTRAINT chk_booking_status CHECK ((status = ANY (ARRAY[1, 2, 3, 4, 5]))),
    CONSTRAINT chk_participants_positive CHECK ((number_of_participants > 0)),
    CONSTRAINT chk_total_amount_positive CHECK ((total_amount >= (0)::numeric))
);


--
-- Name: countries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.countries (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    code character varying(2) NOT NULL,
    name character varying(100) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    display_order integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT chk_country_code_length CHECK ((length((code)::text) = 2)),
    CONSTRAINT chk_display_order CHECK ((display_order >= 0))
);


--
-- Name: email_notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.email_notifications (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid,
    booking_id uuid,
    type integer NOT NULL,
    status integer DEFAULT 1 NOT NULL,
    to_email character varying(255) NOT NULL,
    subject character varying(500) NOT NULL,
    body text NOT NULL,
    sent_at timestamp without time zone,
    retry_count integer DEFAULT 0 NOT NULL,
    error_message text,
    scheduled_for timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT chk_email_format_notification CHECK (((to_email)::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text)),
    CONSTRAINT chk_email_status CHECK ((status = ANY (ARRAY[1, 2, 3, 4]))),
    CONSTRAINT chk_email_type CHECK ((type = ANY (ARRAY[1, 2, 3, 4]))),
    CONSTRAINT chk_retry_count CHECK ((retry_count >= 0))
);


--
-- Name: home_page_content; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.home_page_content (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    hero_title character varying(200) DEFAULT 'Descubre PanamÃ¡'::character varying NOT NULL,
    hero_subtitle character varying(500) DEFAULT 'Explora los destinos mÃ¡s increÃ­bles con nuestros tours exclusivos'::character varying NOT NULL,
    hero_search_placeholder character varying(100) DEFAULT 'Buscar tours...'::character varying NOT NULL,
    hero_search_button character varying(50) DEFAULT 'Buscar'::character varying NOT NULL,
    tours_section_title character varying(200) DEFAULT 'Tours Disponibles'::character varying NOT NULL,
    tours_section_subtitle character varying(300) DEFAULT 'Selecciona tu prÃ³xima aventura'::character varying NOT NULL,
    loading_tours_text character varying(200) DEFAULT 'Cargando tours...'::character varying NOT NULL,
    error_loading_tours_text character varying(300) DEFAULT 'Error al cargar los tours. Por favor, intenta de nuevo.'::character varying NOT NULL,
    no_tours_found_text character varying(200) DEFAULT 'No se encontraron tours disponibles.'::character varying NOT NULL,
    footer_brand_text character varying(100) DEFAULT 'ToursPanama'::character varying NOT NULL,
    footer_description character varying(500) DEFAULT 'Tu plataforma de confianza para descubrir PanamÃ¡'::character varying NOT NULL,
    footer_copyright character varying(200) DEFAULT 'Â© 2024 ToursPanama. Todos los derechos reservados.'::character varying NOT NULL,
    nav_brand_text character varying(100) DEFAULT 'ToursPanama'::character varying NOT NULL,
    nav_tours_link character varying(50) DEFAULT 'Tours'::character varying NOT NULL,
    nav_bookings_link character varying(50) DEFAULT 'Mis Reservas'::character varying NOT NULL,
    nav_login_link character varying(50) DEFAULT 'Iniciar SesiÃ³n'::character varying NOT NULL,
    nav_logout_button character varying(50) DEFAULT 'Cerrar SesiÃ³n'::character varying NOT NULL,
    page_title character varying(200) DEFAULT 'ToursPanama â€” Descubre los Mejores Tours en PanamÃ¡'::character varying NOT NULL,
    meta_description character varying(500) DEFAULT 'Plataforma moderna de reservas de tours en PanamÃ¡. Explora, reserva y disfruta de las mejores experiencias turÃ­sticas.'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone,
    logo_url character varying(500),
    favicon_url character varying(500),
    logo_url_social character varying(500),
    hero_image_url character varying(500)
);


--
-- Name: media_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.media_files (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    file_name character varying(255) NOT NULL,
    file_path character varying(1000) NOT NULL,
    file_url character varying(1000) NOT NULL,
    mime_type character varying(100) NOT NULL,
    file_size bigint NOT NULL,
    alt_text character varying(500),
    description character varying(1000),
    category character varying(100),
    is_image boolean DEFAULT false NOT NULL,
    width integer,
    height integer,
    uploaded_by uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT chk_file_size_positive CHECK ((file_size >= 0)),
    CONSTRAINT chk_height_positive CHECK (((height IS NULL) OR (height > 0))),
    CONSTRAINT chk_width_positive CHECK (((width IS NULL) OR (width > 0)))
);


--
-- Name: pages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pages (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    title character varying(200) NOT NULL,
    slug character varying(200) NOT NULL,
    content text NOT NULL,
    excerpt character varying(500),
    meta_title character varying(200),
    meta_description character varying(500),
    meta_keywords character varying(500),
    is_published boolean DEFAULT false NOT NULL,
    published_at timestamp without time zone,
    template character varying(100),
    display_order integer DEFAULT 0 NOT NULL,
    created_by uuid,
    updated_by uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT chk_display_order_positive CHECK ((display_order >= 0)),
    CONSTRAINT chk_slug_format CHECK (((slug)::text ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text))
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    token character varying(500) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    is_used boolean DEFAULT false NOT NULL,
    used_at timestamp without time zone,
    ip_address character varying(45),
    user_agent character varying(500),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone
);


--
-- Name: TABLE password_reset_tokens; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.password_reset_tokens IS 'Tokens para recuperaciÃ³n de contraseÃ±a. Expiran en 15 minutos y son de un solo uso.';


--
-- Name: COLUMN password_reset_tokens.token; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.password_reset_tokens.token IS 'Token Ãºnico (UUID sin guiones) para resetear contraseÃ±a';


--
-- Name: COLUMN password_reset_tokens.expires_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.password_reset_tokens.expires_at IS 'Fecha y hora de expiraciÃ³n del token (15 minutos desde creaciÃ³n)';


--
-- Name: COLUMN password_reset_tokens.is_used; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.password_reset_tokens.is_used IS 'Indica si el token ya fue utilizado (un solo uso)';


--
-- Name: COLUMN password_reset_tokens.used_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.password_reset_tokens.used_at IS 'Fecha y hora en que se utilizÃ³ el token';


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    booking_id uuid NOT NULL,
    provider integer NOT NULL,
    status integer DEFAULT 1 NOT NULL,
    amount numeric(10,2) NOT NULL,
    provider_transaction_id character varying(255),
    provider_payment_intent_id character varying(255),
    currency character varying(3) DEFAULT 'USD'::character varying NOT NULL,
    authorized_at timestamp without time zone,
    captured_at timestamp without time zone,
    refunded_at timestamp without time zone,
    failure_reason text,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT chk_currency_length CHECK ((length((currency)::text) = 3)),
    CONSTRAINT chk_payment_amount_positive CHECK ((amount > (0)::numeric)),
    CONSTRAINT chk_payment_provider CHECK ((provider = ANY (ARRAY[1, 2, 3]))),
    CONSTRAINT chk_payment_status CHECK ((status = ANY (ARRAY[1, 2, 3, 4, 5])))
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    token character varying(500) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    is_revoked boolean DEFAULT false NOT NULL,
    revoked_at timestamp without time zone,
    replaced_by_token character varying(500),
    ip_address character varying(45),
    user_agent character varying(500),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT chk_expires_at_future CHECK ((expires_at > created_at))
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(50) NOT NULL,
    description text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone
);


--
-- Name: tour_dates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_dates (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tour_id uuid NOT NULL,
    tour_date_time timestamp without time zone NOT NULL,
    available_spots integer DEFAULT 0 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT chk_available_spots_tour_date CHECK ((available_spots >= 0)),
    CONSTRAINT chk_tour_date_future CHECK ((tour_date_time > created_at))
);


--
-- Name: tour_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tour_images (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tour_id uuid NOT NULL,
    image_url character varying(500) NOT NULL,
    alt_text character varying(200),
    display_order integer DEFAULT 0 NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT chk_display_order CHECK ((display_order >= 0))
);


--
-- Name: tours; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tours (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(200) NOT NULL,
    description text NOT NULL,
    itinerary text,
    price numeric(10,2) NOT NULL,
    max_capacity integer NOT NULL,
    duration_hours integer NOT NULL,
    location character varying(200),
    is_active boolean DEFAULT true NOT NULL,
    available_spots integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone,
    includes text,
    tour_date timestamp without time zone,
    CONSTRAINT chk_available_spots CHECK (((available_spots >= 0) AND (available_spots <= max_capacity))),
    CONSTRAINT chk_capacity_positive CHECK ((max_capacity > 0)),
    CONSTRAINT chk_duration_positive CHECK ((duration_hours > 0)),
    CONSTRAINT chk_price_positive CHECK ((price >= (0)::numeric))
);


--
-- Name: COLUMN tours.tour_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.tours.tour_date IS 'Fecha principal del tour. Puede ser null si el tour tiene múltiples fechas en tour_dates';


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(500) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    phone character varying(20),
    is_active boolean DEFAULT true NOT NULL,
    failed_login_attempts integer DEFAULT 0 NOT NULL,
    locked_until timestamp without time zone,
    last_login_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT chk_email_format CHECK (((email)::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text)),
    CONSTRAINT chk_failed_attempts CHECK ((failed_login_attempts >= 0))
);


--
-- Name: countries countries_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_code_key UNIQUE (code);


--
-- Name: countries countries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_pkey PRIMARY KEY (id);


--
-- Name: idx_bookings_country_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bookings_country_id ON public.bookings USING btree (country_id) WHERE (country_id IS NOT NULL);


--
-- Name: idx_countries_active_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_countries_active_order ON public.countries USING btree (is_active, display_order);


--
-- Name: idx_countries_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_countries_code ON public.countries USING btree (code);


--
-- Name: idx_tours_tour_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tours_tour_date ON public.tours USING btree (tour_date) WHERE (tour_date IS NOT NULL);


--
-- Name: bookings fk_bookings_country_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fk_bookings_country_id FOREIGN KEY (country_id) REFERENCES public.countries(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict xWreKFfFtnJhjRqiXQPRHd51pqzu3UPFzcbWT5Ms4kOuS9YXuoTo5fB3W9dXGis

